'use strict';
/*
* This is  a  Plugin. It  provides for integrated music and
* video  playback  tabs.  Use  the  integratedPlayer object
* and the audio and video subobjects to control the embeded
* media player.
*/
var audio,video,integratedPlayer;
function embededPlayer(){
	var audioFile,videoFile,overlay;
	audio = [".mp3",".wav",".flac",".ape",".m4a",".aac",".wma",".ogg",".webm"];
	video = [".webm",".mkv",".flv",".mp4",".ogg",".gif",".avi",".mov",".m4v",".m4p",".3gp"];
	integratedPlayer={
		audio:{
			open:function(fileInfo){
				fileManager.requestChooser();
				fab.remove("integratedAudioPause","integratedAudioPlay","integratedAudioStop");
				try{audioFile.pause();}catch(err){}
				audioFile = new Audio(fs.path({
					type:"file",
					path:fileInfo.fullPath,
					export:"download"
				}));
				audioFile.play();
				audioFile.addEventListener("ended",integratedPlayer.audio.ended);
				fab.add({
					priority:5,
					id:"integratedAudioStop",
					color:"#FF5722",
					img:"system/res/stopLight.svg",
					onclick:integratedPlayer.audio.stop,
					title:"Stop"
				},{
					priority:4,
					id:"integratedAudioPause",
					color:"#FF5722",
					img:"system/res/pause.svg",
					onclick:integratedPlayer.audio.toggle,
					title:"Pause"
				});
				fab.update();
			},
			toggle:function(){
				if(audioFile.paused){
					audioFile.play();
				} else {
					audioFile.pause();
				}
				fab.remove("integratedAudioPlay","integratedAudioPause");
				if(audioFile.paused){
					fab.add({
						priority:4,
						id:"integratedAudioPlay",
						color:"#FF5722",
						img:"system/res/play.svg",
						onclick:integratedPlayer.audio.toggle,
						title:"Play"
					});
				} else {
					fab.add({
						priority:4,
						id:"integratedAudioPause",
						color:"#FF5722",
						img:"system/res/pause.svg",
						onclick:integratedPlayer.audio.toggle,
						title:"Pause"
					});
				}
				fab.update();
			},
			stop:function(){
				try{
					audioFile.pause();
					audioPercentage=0;
					audioFile = null;
				}catch(err){}
				fab.remove("integratedAudioPause","integratedAudioPlay","integratedAudioStop","integratedAudioReplay","integratedAudioCancel");
				fab.update();
			},
			ended:function(){
				fab.remove("integratedAudioPause","integratedAudioPlay","integratedAudioStop");
				fab.add({
					priority:5,
					id:"integratedAudioCancel",
					color:"#FF5722",
					img:"system/res/cancelLight.svg",
					onclick:integratedPlayer.audio.stop,
					title:"Close"
				},{
					priority:4,
					id:"integratedAudioReplay",
					color:"#FF5722",
					img:"system/res/replayLight.svg",
					onclick:integratedPlayer.audio.replay,
					title:"Replay"
				});
				fab.update();
			},
			replay:function(){
				fab.remove("integratedAudioReplay","integratedAudioCancel");
				fab.add({
					priority:5,
					id:"integratedAudioStop",
					color:"#FF5722",
					img:"system/res/stopLight.svg",
					onclick:integratedPlayer.audio.stop,
					title:"Stop"
				},{
					priority:4,
					id:"integratedAudioPause",
					color:"#FF5722",
					img:"system/res/pause.svg",
					onclick:integratedPlayer.audio.toggle,
					title:"Pause"
				});
				fab.update();
				audioFile.play();
			}
		},
		video:{
			open:function(fileInfo){
				fileManager.requestChooser();
				integratedPlayer.video.stop();
				videoFile = document.createElement("video");
				let videoSource = document.createElement("source");
				videoSource.setAttribute("src",fs.path({
					type:"file",
					path:fileInfo.fullPath,
					export:"download"
				}));
				videoFile.appendChild(videoSource);
				videoFile.setAttribute("class","smallVideo");
				videoFile.setAttribute("id","videoFile");
				document.body.appendChild(videoFile);
				videoFile.play();
				videoFile.addEventListener("ended",integratedPlayer.video.ended);
				fab.add({
					priority:2,
					id:"integratedVideoStop",
					color:"#F44336",
					img:"system/res/stopLight.svg",
					onclick:integratedPlayer.video.stop,
					title:"Stop"
				},{
					priority:3,
					id:"integratedVideoEnterFullscreen",
					color:"#F44336",
					img:"system/res/enterFullscreenLight.svg",
					onclick:integratedPlayer.video.toggleFullscreen,
					title:"Pause"
				},{
					priority:1,
					id:"integratedVideoPause",
					color:"#F44336",
					img:"system/res/pause.svg",
					onclick:integratedPlayer.video.toggle,
					title:"Pause"
				});
				fab.update();
			},
			toggleFullscreen:function(){
				fab.remove("integratedVideoExitFullscreen","integratedVideoEnterFullscreen");
				if(videoFile.className=="smallVideo"){
					fab.add({
						priority:3,
						id:"integratedVideoExitFullscreen",
						color:"#F44336",
						img:"system/res/exitFullscreenLight.svg",
						onclick:integratedPlayer.video.toggleFullscreen,
						title:"Exit Fullscreen"
					});
					overlay = document.createElement("div");
					overlay.setAttribute("class","overlay");
					overlay.style.zIndex="2";
					overlay.style.backgroundColor="rgba(0,0,0,1)";
					document.body.appendChild(overlay);
					videoFile.setAttribute("style","");
					videoFile.setAttribute("class","fullVideo");
					document.documentElement.webkitRequestFullscreen();
				} else {
					fab.add({
						priority:4,
						id:"integratedVideoEnterFullscreen",
						color:"#F44336",
						img:"system/res/enterFullscreenLight.svg",
						onclick:integratedPlayer.video.toggleFullscreen,
						title:"Enter Fullscreen"
					});
					document.body.removeChild(overlay);
					videoFile.setAttribute("style","");
					videoFile.setAttribute("class","smallVideo");
					document.webkitExitFullscreen();
				}
				fab.update();
			},
			stop:function(){
				try{
					if(videoFile.className=="fullVideo"){
						document.webkitExitFullscreen();
					}
					videoFile.pause();
				}catch(err){}
				try{
					document.body.removeChild(videoFile);
				}catch(err){}
				try{
					docuemnt.body.removeChild(overlay);
				}catch(err){}
				fab.remove("integratedVideoEnterFullscreen","integratedVideoExitFullscreen","integratedVideoPause","integratedVideoPlay","integratedVideoStop","integratedVideoReplay","integratedVideoCancel");
				fab.update();
			},
			ended:function(){
				fab.remove("integratedVideoPause","integratedVideoPlay","integratedVideoStop");
				fab.add({
					priority:5,
					id:"integratedVideoCancel",
					color:"#F44336",
					img:"system/res/cancelLight.svg",
					onclick:integratedPlayer.video.stop,
					title:"Close"
				},{
					priority:4,
					id:"integratedVideoReplay",
					color:"#F44336",
					img:"system/res/replayLight.svg",
					onclick:integratedPlayer.video.replay,
					title:"Replay"
				});
				fab.update();
			},
			replay:function(){
				fab.remove("integratedVideoCancel","integratedVideoEnterFullscreen","integratedVideoReplay","integratedVideoExitFullscreen");
				fab.add({
					priority:2,
					id:"integratedVideoStop",
					color:"#F44336",
					img:"system/res/stopLight.svg",
					onclick:integratedPlayer.video.stop,
					title:"Stop"
				},{
					priority:3,
					id:"integratedVideoEnterFullscreen",
					color:"#F44336",
					img:"system/res/enterFullscreenLight.svg",
					onclick:integratedPlayer.video.toggleFullscreen,
					title:"Pause"
				},{
					priority:1,
					id:"integratedVideoPause",
					color:"#F44336",
					img:"system/res/pause.svg",
					onclick:integratedPlayer.video.toggle,
					title:"Pause"
				});
				fab.update();
				videoFile.currentTime = 0;
				videoFile.play();
				checkVideoTick();
			},
			toggle:function(){
				fab.remove("integratedVideoPause","integratedVideoPlay");
				if(videoFile.paused){
					fab.add({
						priority:1,
						id:"integratedVideoPause",
						color:"#F44336",
						img:"system/res/pause.svg",
						onclick:integratedPlayer.video.toggle,
						title:"Pause"
					});
					try{
						videoFile.play();
					}catch(err){}
				} else {
					fab.add({
						priority:1,
						id:"integratedVideoPlay",
						color:"#F44336",
						img:"system/res/play.svg",
						onclick:integratedPlayer.video.toggle,
						title:"Play"
					});
					try{
						videoFile.pause();
					}catch(err){}
				}
				fab.update();
			}
		}
	}
}
embededPlayer();