'use strict';
/*
* This  is  a  Plugin. It provides for dedicated music and
* video  playback  tabs.  Use  the  musicTools  Object  to 
* control music tabs, and the videoTools Object to control
* the video tab.  videoCollection  and audioCollection are
* both arrays that contain cached lists of playable files.
* musicLock  and videoLock are both indicaters that a file
* hasn't isn't done for handling yet.
*/
var musicTools,videoTools;
function media(){
	var currentAudio,audioFileTypes,resumeTrack,musicCollection,videoCollection,videoFileTypes,currentVideo,resumeVideo,musicLock,videoLock,overlay;
	audioFileTypes=["mp3","wav","flac","ape","m4a","aac","wma","ogg","webm"];
	videoFileTypes=["mp4","webm","mkv","flv","vob","ogg","ogv","gif","gifv","avi","mov","yuv","asf","m4p","m4v","mpeg","mpg","m2v","m4v","3gp","3g2","f4v"];
	musicLock=false;
	videoLock=false;
	musicTools={
		userLeft:true,
		play:function(song){
			musicLock=true;
			resumeTrack=song;
			if(!!currentAudio){
				currentAudio.pause();
			}
			ui.header.reset({
				color:"#FF9800"
			});
			currentAudio=new Audio(
				fs.path({
					type:"file",
					path:song.fullPath,
					export:"download"
				})
			);
			currentAudio.addEventListener("ended",musicTools.ended);
			ui.header.add({
				message:"Music",
				onclick:musicTools.showMenu
			},{
				message:">"
			},{
				message:song.name,
				onclick:function(){}
			});
			fab.remove("musicToolsStop","musicToolsPause","musicToolsPlay");
			fab.add({
				priority:5,
				id:"musicToolsStop",
				color:"#FF9800",
				img:"system/res/stopLight.svg",
				onclick:musicTools.stop,
				title:"Stop"
			},{
				priority:7,
				id:"musicToolsPause",
				color:"#FF9800",
				img:"system/res/pause.svg",
				onclick:musicTools.pause,
				title:"Pause"
			});
			fab.update();
			currentAudio.play();
		},
		stop:function(){
			musicLock=false;
			if(!musicTools.userLeft){
				ui.header.reset({
					color:"#FF9800"
				});
				ui.header.add({
					message:"Music",
					onclick:musicTools.showMenu
				});
			}
			fab.remove("musicToolsStop","musicToolsPause","musicToolsPlay");
			fab.close();
			currentAudio.pause();
			currentAudio=null;
		},
		pause:function(){
			currentAudio.pause();
			fab.remove("musicToolsPause");
			fab.add({
				priority:7,
				id:"musicToolsPlay",
				color:"#FF9800",
				img:"system/res/play.svg",
				onclick:musicTools.resume,
				title:"Play"
			});
			fab.update();
		},
		resume:function(){
			currentAudio.play();
			fab.remove("musicToolsPlay");
			fab.add({
				priority:7,
				id:"musicToolsPause",
				color:"#FF9800",
				img:"system/res/pause.svg",
				onclick:musicTools.pause,
				title:"Pause"
			});
			fab.update();
		},
		ended:function(){
			musicLock=false;
			ui.header.reset({
				color:"#FF9800"
			});
			ui.header.add({
				message:"Music",
				onclick:musicTools.showMenu
			});
			fab.remove("musicToolsStop","musicToolsPause","musicToolsPlay");
			fab.add({
				priority:7,
				id:"musicToolsReplay",
				color:"#FF9800",
				img:"system/res/replayLight.svg",
				onclick:musicTools.replay,
				title:"Replay"
			},{
				priority:8,
				id:"musicToolsCancel",
				color:"#FF9800",
				img:"system/res/cancelLight.svg",
				onclick:function(){fab.remove("musicToolsCancel","musicToolsReplay");},
				title:"Cancel"
			});
			fab.update();
			currentAudio=null;
		},
		replay:function(){
			fab.remove("musicToolsCancel","musicToolsReplay");
			musicTools.play(resumeTrack);
		},
		shuffle:function(){
			fab.close();
			var tempMusic=musicCollection[Math.floor(Math.random()*musicCollection.length)];
			musicTools.play(tempMusic);
		},
		showMenu:function(){//Triggered after user clicks into music tab
			hamburgerMenu.close();
			musicTools.userLeft=false;
			ui.header.reset({
				color:"#FF9800"
			});
			ui.body.reset();
			ui.header.add({
				message:"Music",
				onclick:musicTools.showMenu
			});
			fs.recursivelyScandir({path:"/",callback:musicTools.listMusic});
			fab.remove("musicToolsShuffle");
			if(musicLock){
				if(currentAudio.paused){
					fab.remove("musicToolsPlay");
					fab.add({
						priority:7,
						id:"musicToolsPlay",
						color:"#FF9800",
						img:"system/res/play.svg",
						onclick:musicTools.resume,
						title:"Play"
					});
				}else{
					fab.remove("musicToolsPause");
					fab.add({
						priority:7,
						id:"musicToolsPause",
						color:"#FF9800",
						img:"system/res/pause.svg",
						onclick:musicTools.pause,
						title:"Pause"
					});
				}
			}
			fab.add({
				priority:6,
				id:"musicToolsShuffle",
				color:"#FF9800",
				img:"system/res/shuffle.svg",
				onclick:musicTools.shuffle,
				position:"vertical",
				title:"Shuffle"
			});
		},
		listMusic:function(data){//asynchronous callback when initially clicked
			musicCollection=[];
			for(let i=0;i!=data.files.length;i++){
				if(audioFileTypes.indexOf(data.files[i].type)!=-1){
					musicCollection[musicCollection.length]=data.files[i];
					ui.body.add({
						message:data.files[i].name,
						onclick:musicTools.play.bind(this,data.files[i]),
						img:[{
							src:"system/res/audioFileBlack.svg",
							align:"left"
						}]
					});
				}
			}
		}
	};
	videoTools={
		userLeft:true,
		play:function(video){
			videoLock=true;
			resumeVideo=video;
			if(!!currentVideo){
				currentVideo.pause();
			}
			ui.header.reset({
				color:"#F44336"
			});
			currentVideo=document.createElement("video");
			let videoSource = document.createElement("source");
			videoSource.setAttribute("src",fs.path({
				type:"file",
				path:video.fullPath,
				export:"download"
			}));
			currentVideo.appendChild(videoSource);
			currentVideo.setAttribute("class","smallVideo");
			currentVideo.setAttribute("id","videoFile");
			document.body.appendChild(currentVideo);
			currentVideo.addEventListener("ended",videoTools.ended);
			ui.header.add({
				message:"Videos",
				onclick:videoTools.showMenu
			},{
				message:">"
			},{
				message:video.name,
				onclick:function(){}
			});
			fab.remove("videoToolsStop","videoToolsPause","videoToolsPlay");
			fab.add({
				priority:5,
				id:"videoToolsStop",
				color:"#F44336",
				img:"system/res/stopLight.svg",
				onclick:videoTools.stop,
				title:"Stop"
			},{
				priority:7,
				id:"videoToolsPause",
				color:"#F44336",
				img:"system/res/pause.svg",
				onclick:videoTools.pause,
				title:"Pause"
			},{
				priority:4,
				id:"videoToolsEnterFS",
				color:"#F44336",
				img:"system/res/enterFullscreenLight.svg",
				onclick:videoTools.toggleFullscreen,
				title:"Enter Fullscreen"
			});
			fab.update();
			currentVideo.play();
		},
		stop:function(){
			videoLock=false;
			if(!videoTools.userLeft){
				ui.header.reset({
					color:"#F44336"
				});
				ui.header.add({
					message:"Videos",
					onclick:videoTools.showMenu
				});
			}
			fab.remove("videoToolsStop","videoToolsPause","videoToolsPlay","videoToolsEnterFS","videoToolsExitFS");
			fab.close();
			currentVideo.pause();
			document.body.removeChild(currentVideo);
			currentVideo=null;
		},
		pause:function(){
			currentVideo.pause();
			fab.remove("videoToolsPause");
			fab.add({
				priority:7,
				id:"videoToolsPlay",
				color:"#F44336",
				img:"system/res/play.svg",
				onclick:videoTools.resume,
				title:"Play"
			});
			fab.update();
		},
		resume:function(){
			currentVideo.play();
			fab.remove("videoToolsPlay");
			fab.add({
				priority:7,
				id:"videoToolsPause",
				color:"#F44336",
				img:"system/res/pause.svg",
				onclick:videoTools.pause,
				title:"Pause"
			});
			fab.update();
		},
		ended:function(){
			videoLock=false;
			ui.header.reset({
				color:"#F44336"
			});
			ui.header.add({
				message:"Videos",
				onclick:videoTools.showMenu
			});
			fab.remove("videoToolsStop","videoToolsPause","videoToolsPlay");
			fab.add({
				priority:7,
				id:"videoToolsReplay",
				color:"#F44336",
				img:"system/res/replayLight.svg",
				onclick:videoTools.replay,
				title:"Replay"
			},{
				priority:8,
				id:"videoToolsCancel",
				color:"#F44336",
				img:"system/res/cancelLight.svg",
				onclick:function(){fab.remove("videoToolsReplay","videoToolsCancel");},
				title:"Cancel"
			});
			fab.update();
			currentVideo=null;
		},
		replay:function(){
			fab.remove("videoToolsCancel","videoToolsCancel");
			videoTools.play(resumeVideo);
		},
		toggleFullscreen:function(){
			fab.remove("videoToolsExitFS","videoToolsEnterFS");
			if(currentVideo.className=="smallVideo"){
				fab.add({
					priority:3,
					id:"videoToolsExitFS",
					color:"#F44336",
					img:"system/res/exitFullscreenLight.svg",
					onclick:videoTools.toggleFullscreen,
					title:"Exit Fullscreen"
				});
				overlay = document.createElement("div");
				overlay.setAttribute("class","overlay");
				overlay.style.zIndex="2";
				overlay.style.backgroundColor="rgba(0,0,0,1)";
				document.body.appendChild(overlay);
				currentVideo.setAttribute("style","");
				currentVideo.setAttribute("class","fullVideo");
				document.documentElement.webkitRequestFullscreen();
			} else {
				fab.add({
					priority:4,
					id:"videoToolsEnterFS",
					color:"#F44336",
					img:"system/res/enterFullscreenLight.svg",
					onclick:videoTools.toggleFullscreen,
					title:"Enter Fullscreen"
				});
				document.body.removeChild(overlay);
				currentVideo.setAttribute("style","");
				currentVideo.setAttribute("class","smallVideo");
				document.webkitExitFullscreen();
			}
			fab.update();
		},
		jumpStart:function(){
			videoTools.play(videoCollection[0]);
		},
		showMenu:function(){//Triggered after user clicks into video tab
			hamburgerMenu.close();
			videoTools.userLeft=false;
			ui.header.reset({
				color:"#F44336"
			});
			ui.body.reset();
			ui.header.add({
				message:"Videos",
				onclick:videoTools.showMenu
			});
			fs.recursivelyScandir({path:"/",callback:videoTools.listVideos});
			if(videoLock){
				if(currentVideo.paused){
					fab.add({
						priority:7,
						id:"videoToolsPlay",
						color:"#F44336",
						img:"system/res/play.svg",
						onclick:videoTools.resume,
						title:"Play"
					});
				}else{
					fab.add({
						priority:7,
						id:"videoToolsPause",
						color:"#F44336",
						img:"system/res/pause.svg",
						onclick:videoTools.pause,
						title:"Pause"
					});
				}
				if(currentVideo.className=="smallVideo"){/*The video is currently not in full screen. We need to give the user the ability to enter full screen.*/
					fab.add({
						priority:4,
						id:"videoToolsEnterFS",
						color:"#F44336",
						img:"system/res/enterFullscreenLight.svg",
						onclick:videoTools.toggleFullscreen,
						title:"Enter Fullscreen"
					});
				}else{
					fab.add({
						priority:3,
						id:"videoToolsExitFS",
						color:"#F44336",
						img:"system/res/exitFullscreenLight.svg",
						onclick:videoTools.toggleFullscreen,
						title:"Exit Fullscreen"
					});
				}
			}else{
				fab.add({
					priority:6,
					id:"videoToolsPlay",
					color:"#F44336",
					img:"system/res/play.svg",
					onclick:videoTools.jumpStart,
					position:"vertical",
					title:"Play"
				});
			}
		},
		listVideos:function(data){//asynchronous callback when initially clicked
			videoCollection=[];
			for(let i=0;i!=data.files.length;i++){
				if(videoFileTypes.indexOf(data.files[i].type)!=-1){
					videoCollection[videoCollection.length]=data.files[i];
					ui.body.add({
						message:data.files[i].name,
						onclick:videoTools.play.bind(this,data.files[i]),
						img:[{
							src:"system/res/videoDark.svg",
							align:"left"
						}]
					});
				}
			}
		}
	};
	hamburgerMenu.add({
		priority:4,
		id:"stockMusic",
		title:"Music",
		img:"system/res/musicLight.svg",
		onclick:musicTools.showMenu,
		color:"#FF9800",
		/*Intentially left out musicToolsStop, so that user can stop playing music.*/
		unload:function(){musicTools.userLeft=true;fab.remove("musicToolsPlay","musicToolsPause","musicToolsReplay","musicToolsShuffle","musicToolsCancel");}
	});
	hamburgerMenu.add({
		priority:3,
		id:"stockVideo",
		title:"Videos",
		img:"system/res/videoLight.svg",
		onclick:videoTools.showMenu,
		color:"#F44336",
		/*Intentially left out videoToolsStop, so that user can stop playing music.*/
		unload:function(){videoTools.userLeft=true;fab.remove("videoToolsPlay","videoToolsPause","videoToolsReplay","videoToolsExitFS","videoToolsEnterFS","videoToolsCancel");}
	});
}
media();